// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopApi.Data;

#nullable disable

namespace ShopApi.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20251019160819_InitShopDb")]
    partial class InitShopDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<string>("NrOfUses")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nr_of_uses");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("RelevantRoles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relevant_roles");

                    b.HasKey("ItemId");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ItemDescription = "Protects from one Vampire attack automatically per night",
                            ItemName = "Garlic",
                            NrOfUses = "1",
                            Price = 50,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 2,
                            ItemDescription = "Can block a kill attempt or be used by Mafia to kill a player",
                            ItemName = "Silver Dagger",
                            NrOfUses = "1",
                            Price = 60,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 3,
                            ItemDescription = "Required to save a player at night",
                            ItemName = "Healing Herbs",
                            NrOfUses = "3",
                            Price = 80,
                            RelevantRoles = "4"
                        },
                        new
                        {
                            ItemId = 4,
                            ItemDescription = "Reduces chance of being detected by Detective, Spy, or rumor by 60%",
                            ItemName = "Cloak",
                            NrOfUses = "unlimited",
                            Price = 100,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 5,
                            ItemDescription = "Secretly eliminates a player",
                            ItemName = "Poison",
                            NrOfUses = "1",
                            Price = 60,
                            RelevantRoles = "1"
                        },
                        new
                        {
                            ItemId = 6,
                            ItemDescription = "Starts false rumors",
                            ItemName = "Rumor Scroll",
                            NrOfUses = "2",
                            Price = 80,
                            RelevantRoles = "2"
                        },
                        new
                        {
                            ItemId = 7,
                            ItemDescription = "Grants extra coins for completing tasks",
                            ItemName = "Coin Purse",
                            NrOfUses = "unlimited",
                            Price = 100,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 8,
                            ItemDescription = "Heals the user once",
                            ItemName = "First Aid Kit",
                            NrOfUses = "1",
                            Price = 50,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 9,
                            ItemDescription = "Blocks one Mafia kill attempt per night",
                            ItemName = "Bullet Proof Vest",
                            NrOfUses = "1",
                            Price = 60,
                            RelevantRoles = "3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 10,
                            ItemDescription = "Protects items from being examined by others",
                            ItemName = "Lockbox",
                            NrOfUses = "unlimited",
                            Price = 100,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 11,
                            ItemDescription = "Temporarily changes player’s role appearance in investigations or rumors",
                            ItemName = "Disguise Kit",
                            NrOfUses = "1",
                            Price = 60,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 12,
                            ItemDescription = "50% chance to block a Vampire or Mafia attack",
                            ItemName = "Lucky Charm",
                            NrOfUses = "3",
                            Price = 80,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 13,
                            ItemDescription = "Eavesdrops on secret messages in Speakeasy or Back Alley",
                            ItemName = "Listening Device",
                            NrOfUses = "2",
                            Price = 60,
                            RelevantRoles = "1,2,3,4,5,6,8"
                        },
                        new
                        {
                            ItemId = 14,
                            ItemDescription = "Required for investigations",
                            ItemName = "Magnifying Glass",
                            NrOfUses = "3",
                            Price = 80,
                            RelevantRoles = "2,3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
